export const SET_LOADER_VISIBLE = 'SET_LOADER_VISIBLE';
export const SET_LIST_LOADER_VISIBLE = 'SET_LIST_LOADER_VISIBLE';
export const SET_BEFORE_LIST_LOADER_VISIBLE = 'SET_BEFORE_LIST_LOADER_VISIBLE';
export const STORIES_LIST = 'STORIES_LIST';
export const GET_STORIES_LIST = 'GET_STORIES_LIST';
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
